#!/bin/bash
set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

RESOURCES_PATH=$(realpath $(scriptPath)/../resources/)

juju attach twister twister-src=$RESOURCES_PATH/twister_src.tar.gz
juju attach twister db-template=$RESOURCES_PATH/twister_demo.sql
juju attach vnflcv vnflcv-src=$RESOURCES_PATH/vnflcv.tar.gz

juju wait -m $JUJU_CONTROLLER:$JUJU_MODEL

TWISTER_ADDR=$(unitAddress twister)
VNFLCV_ADDR=$(unitAddress vnflcv)
KIBANA_ADDR=$(unitAddress kibanaspirent)

sudo tee /etc/rinetd.conf &> /dev/null << EOF
# Kibana
0.0.0.0 5601 ${KIBANA_ADDR} 8888

# vnflcv
0.0.0.0 8080 ${VNFLCV_ADDR} 8080
0.0.0.0 8081 ${VNFLCV_ADDR} 8081

# Twister
0.0.0.0 8000 ${TWISTER_ADDR} 8000

# logging information
logfile /var/log/rinetd.log
EOF

sudo service rinetd restart &> /dev/null

juju run-action kibanaspirent/0 load-dashboard dashboard=vnflcv &> /dev/null
juju run-action twister/0 restart &> /dev/null

exposeResult "Applications Ready" 0 "true"

