#!/bin/bash

set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

sudo sysctl -w vm.max_map_count=262144 &> /dev/null
sudo apt-get update &> /dev/null
sudo apt-get -y install rinetd &> /dev/null

setResult "Prepare successful."
exit 0
