#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

service vnflcv-rest start
service vnflcv-ui start

open-port 8080
open-port 8081
status-set active "Ready"
