OPERATION_SUCCESS = 'SUCCESS'
OPERATION_FAILED = 'FAILED'
OPERATION_PENDING = 'PENDING'
OPERATION_FINAL_STATES = [OPERATION_SUCCESS, OPERATION_FAILED]

OPENSTACK_VNF_STATES_MAPPING = {'ACTIVE': OPERATION_SUCCESS,
                                'ERROR': OPERATION_FAILED,
                                'PENDING_CREATE': OPERATION_PENDING,
                                'PENDING_DELETE': OPERATION_PENDING}
