# This software is confidential and proprietary to Spirent Communications Inc.
# No part of this software may be reproduced, transmitted, disclosed or used
# in violation of the Software License Agreement without the expressed
# written consent of Spirent Communications Inc.
#
#


# This structure was written in accordance with section 7.1.5.2 of ETSI GS NFV-IFA 011 - v2.4.1 (2018-02).

ChangeVnfFlavourOpConfig:
    description: This information element defines attributes that affect the invocation of the ChangeVnfFlavour operation.
    attributes:
        parameter:
            description: Array of KVP requirements for VNF-specific parameters to be passed when invoking the ChangeVnfFlavour operation. See note
            type: List
            required: False
            constraints:
                entry_type: NotSpecified

