# This structure was written in accordance with section 7.1.5.6 of ETSI GS NFV-IFA 011 - v2.1.1 (2016-10).

HealVnfOpConfig:
  description: This information element defines attributes that affect the invocation of the HealVnf operation.
  attributes:
    parameter:
      description: VNF-specific parameter to be passed when invoking the HealVnf operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified

    cause:
      description: Supported "cause" parameter values.
      type: List
      required: false
      constraints:
        entry_type: String
