# This structure was written in accordance with section 7.1.5.3 of ETSI GS NFV-IFA 011 - v2.1.1 (2016-10).

InstantiateVnfOpConfig:
  description: This information element defines attributes that affect the invocation of the InstantiateVnf operation.
  attributes:
    parameter:
      description: VNF-specific parameter to be passed when invoking the InstantiateVnf operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified
