# This structure was written in accordance with section 7.1.5.8 of ETSI GS NFV-IFA 011 - v2.1.1 (2016-10).

OperateVnfOpConfig:
  description: This information element defines attributes that affect the invocation of the OperateVnf operation.
  attributes:
    min_graceful_stop_timeout:
      description: Minimum timeout value for graceful stop of a VNF instance.
      type: Number
      required: true

    max_recommended_graceful_stop_timeout :
      description: Maximum recommended timeout value that can be needed to gracefully stop a VNF instance of a particular type under certain conditions, such as maximum load condition. This is provided by VNF provider as information for the operator facilitating the selection of optimal timeout value. This value is not used as constraint.
      type: Number
      required: false
