#
# Copyright (c) 2018 by Spirent Communications Plc.
# All Rights Reserved.
#
# This software is confidential and proprietary to Spirent Communications Inc.
# No part of this software may be reproduced, transmitted, disclosed or used
# in violation of the Software License Agreement without the expressed
# written consent of Spirent Communications Inc.
#
#


# This structure was written in accordance with section 7.1.5.5 of ETSI GS NFV-IFA 011 - v2.1.1 (2016-10).

ScaleVnfToLevelOpConfig:
  description: This information element defines attributes that affect the invocation of the ScaleVnf operation.
  attributes:
    parameter:
      description: Array of KVP requirements for VNF-specific parameters to be passed when invoking the ScaleVnfToLevel operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified

    arbitrary_target_levels_supported:
      description: Signals whether scaling according to the parameter "scaleInfo" is supported by this VNF.
      type: Boolean
      required: true
