# This structure was written in accordance with section 7.1.5.5 of ETSI GS NFV-IFA 011 - v2.1.1 (2016-10).

ScaleVnfToLevelOpConfig:
  description: This information element defines attributes that affect the invocation of the ScaleVnf operation.
  attributes:
    parameter:
      description: VNF-specific parameter to be passed when invoking the ScaleVnfToLevel operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified

    arbitrary_target_levels_supported:
      description: Signals whether scaling according to the parameter "scaleInfo" is supported by this VNF.
      type: Boolean
      required: true
