#
# Copyright (c) 2018 by Spirent Communications Plc.
# All Rights Reserved.
#
# This software is confidential and proprietary to Spirent Communications Inc.
# No part of this software may be reproduced, transmitted, disclosed or used
# in violation of the Software License Agreement without the expressed
# written consent of Spirent Communications Inc.
#
#


# This structure was written in accordance with section 7.1.5.4 of ETSI GS NFV-IFA 011 - v2.4.1 (2018-02).

ScaleVnfOpConfig:
  description: This information element defines attributes that affect the invocation of the ScaleVnf operation.
  attributes:
    parameter:
      description: Array of KVP requirements for VNF-specific parameters to be passed when invoking the ScaleVnf operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified

    scaling_by_more_than_one_step_supported:
      description: Signals whether passing a value larger than one in the numScalingSteps parameter of the ScaleVnf operation is supported by this VNF. Default is FALSE, i.e. "not supported".
      type: Boolean
      required: false
