#
# Copyright (c) 2018 by Spirent Communications Plc.
# All Rights Reserved.
#
# This software is confidential and proprietary to Spirent Communications Inc.
# No part of this software may be reproduced, transmitted, disclosed or used
# in violation of the Software License Agreement without the expressed
# written consent of Spirent Communications Inc.
#
#


# This structure was written in accordance with section 7.1.6.7 of ETSI GS NFV-IFA 011 - v2.4.1 (2018-02).

VnfcConfigurableProperties:
  description: This information element defines the configurable properties of a VNFC. For a VNFC instance, the value of these properties can be modified through the VNFM.
  attributes:
    additional_vnfc_configurable_property:
      description: It provides VNFC configurable properties that can be modified using the ModifyVnfInfo operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified
