#
# Copyright (c) 2018 by Spirent Communications Plc.
# All Rights Reserved.
#
# This software is confidential and proprietary to Spirent Communications Inc.
# No part of this software may be reproduced, transmitted, disclosed or used
# in violation of the Software License Agreement without the expressed
# written consent of Spirent Communications Inc.
#
#


# This structure was written in accordance with section 7.1.12 of ETSI GS NFV-IFA 011 - v2.4.1 (2018-02).

VnfConfigurableProperties:
  description: This information element defines the configurable properties of a VNF (e.g. related to auto scaling and auto healing). For a VNF instance, the value of these properties can be modified by the VNFM.
  attributes:
    is_auto_scale_enables:
      description: It permits to enable (TRUE) / disable (FALSE) the auto-scaling functionality.
      type: Boolean
      required: false

    is_auto_heal_enabled:
      description: It permits to enable (TRUE) / disable (FALSE) the auto-healing functionality.
      type: Boolean
      required: false

    additional_configurable_property:
      description: It provides VNF specific configurable properties that can be modified using the ModifyVnfConfiguration operation.
      type: List
      required: false
      constraints:
        entry_type: NotSpecified
