#!/bin/bash
set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

TWISTER_ADDR=$(unitAddress twister)
VNFLCV_ADDR=$(unitAddress vnflcv)
KIBANA_ADDR=$(unitAddress kibanaspirent)

sudo tee /etc/rinetd.conf &> /dev/null << EOF
# Kibana
0.0.0.0 5601 ${KIBANA_ADDR} 8888

# vnflcv
0.0.0.0 8080 ${VNFLCV_ADDR} 8080
0.0.0.0 8081 ${VNFLCV_ADDR} 8081

# Twister
0.0.0.0 8000 ${TWISTER_ADDR} 8000

# logging information
logfile /var/log/rinetd.log
EOF

sudo service rinetd restart &> /dev/null

setResult "Rinetd successfully configured."
exit 0
